apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-proxy
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`http.traefik.me`)
      kind: Rule
      services:
        - name: traefic-demo
          port: 80
