apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: mtlsoption                          
  namespace: default

spec:
  minVersion: VersionTLS12                     
  maxVersion: VersionTLS13                    
  curvePreferences:                           
    - CurveP521
    - CurveP384
  cipherSuites:                               
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  clientAuth:                                
    secretNames:                             
      - secret-ca
    clientAuthType: VerifyClientCertIfGiven    
  sniStrict: false

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mtls-proxy
  annotations:
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mtls.traefik.me`)
      kind: Rule
      services:
        - name: traefic-demo
          port: 80
  tls:
    secretName: mtls-cert-store
    options:
      name: mtlsoption
      namespace: default
          
